services:
  mongodb:
    image: mongo:8.2
    container_name: easy-auth-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: easy-auth-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    ports:
      - '8081:8081'
    depends_on:
      - mongodb

  mailpit:
    image: axllent/mailpit:latest
    container_name: easy-auth-mailpit
    restart: unless-stopped
    ports:
      - '8025:8025'
      - '1025:1025'
    volumes:
      - mailpit_data:/data
    environment:
      - MP_DATABASE=/data/mailpit.db
      - MP_MAX_MESSAGES=5000
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
      - TZ=UTC # Set the timezone

volumes:
  mongodb_data:
  mailpit_data:
